### ISSUE TITLE
Missing Grammar Documentation

### ISSUE THREAD

**Issue by donsmart86** [phorward/pynetree#1]
Please provide a description of the BNF-like grammar language.

**Comment by phorward** [comment]
Hello @donsmart86,

currently I'm not doing any further development on Pynetree. It shares the same BNF language as [phorward 0.19](https://github.com/phorward/phorward/blob/v0.19.0/src/parse/bnf.syn) did, but it was changed during the last year. 

Maybe the BNF definition above helps to understand the syntax more precisely. I'm closing this issue for now.
